stages:
  train:
    cmd: python src/train.py
    deps:
    - data/iris.data
    - src/train.py
    outs:
    - data/predict.txt
    plots:
    - data/importances.csv:
        cache: false
        template: bar_horizontal
        x: feature_importance
        y: feature_name
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/iris.data
    - data/predict.txt
    - src/evaluate.py
    metrics:
    - data/metrics.json
    plots:
    - data/classes.csv:
        cache: false
        template: confusion
        x: actual
        y: predicted
